### ISSUE TITLE
Supplied proguard file does not work

### ISSUE THREAD

**Issue by alxndrsn** [Simprints/LibSimprints#13]
Using the proguard file supplied at https://github.com/Simprints/LibSimprints/blob/master/proguard-rules.pro, I get the following error:
```
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.simprints.libsimprints.Registration
        at android.os.Parcel.readParcelableCreator(Parcel.java:2438)
        at android.os.Parcel.readParcelable(Parcel.java:2359)
        at android.os.Parcel.readValue(Parcel.java:2265)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2620)
        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
        at android.os.BaseBundle.containsKey(BaseBundle.java:269)
        at android.content.Intent.hasExtra(Intent.java:6047)
        ...
```
I found the following proguard configuration to work successfully:
```
-keep class * implements android.os.Parcelable {
    *;
}
```

**Comment by alxndrsn** [comment]
Better yet:
```
-keep class com.simprints.libsimprints.* implements android.os.Parcelable {
    *;
}
```
